version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo Build started on 'date'
      - cp index.html /var/www/html/

  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - index.html
